name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: |
          echo "hello world"
      - name: checkout
        uses: actions/checkout@v3
