name: Hello World

on:
  push:
    branches:
      - main

jobs:
build:
runs-on: ubuntu-latest
strategy:
  matrix:
  node-version: [20.x]

  deploying:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"
